name: deepesdl
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - bottleneck
  - dask=2022.9.2
  - netcdf4
  - numpy
  - pandas
  - python=3.9
  - requests
  - rioxarray=0.12.2
  - scipy
  - spyndex
  - xarray=2022.9.0
  - xcube
  - xcube-cds
  - xcube-sh
  - xcube-cmems
  - xcube-cci
  - xcube_geodb
  - yaml
  - zarr=2.11.3
